const products = [{
    id: 1,
    accessory: "Sea life",
    background: "Moon and birds",
    expression: "Brown eyes",
    hairstyle: "Long and straight",
    name: "Miya",
    outfit: "Winter",
    prop: null,
}, {
    id: 2,
    accessory: null,
    background: "Night & sky",
    expression: "Brown eyes",
    hairstyle: "Double ponies",
    name: "Rina",
    outfit: "Astronaut",
    prop: null,
}, {
    id: 3,
    accessory: null,
    background: "Sun & mucha",
    expression: "Brown eyes",
    hairstyle: "Pixie",
    name: "Aubreeanna",
    outfit: "Steampunk",
    prop: "Skateboard",
}, {
    id: 4,
    accessory: null,
    background: "Amai",
    expression: "Gaze right",
    hairstyle: "Short bob",
    name: "Aubreeanna",
    outfit: "Steampunk",
    prop: "Skateboard",
}, {
    id: 5,
    accessory: null,
    background: "Casino",
    expression: "Gaze close",
    hairstyle: "Short bob",
    name: "Yeeun",
    outfit: "Steampunk",
    prop: "Cell phone",
}, {
    id: 6,
    accessory: "Headphones",
    background: "Sun & mucha",
    expression: "Brown eyes",
    hairstyle: "Ponytail",
    name: "Kotoko",
    outfit: "Kotoko",
    prop: "Skateboard",
}, {
    id: 7,
    accessory: null,
    background: "Sun & mucha",
    expression: "Brown eyes",
    hairstyle: "Double ponies",
    name: "Sinead",
    outfit: "Steampunk",
    prop: "Lolipop",
}, {
    id: 8,
    accessory: null,
    background: "Night & sky",
    expression: "Brown eyes",
    hairstyle: "Bangs & buns",
    name: "Ataya",
    outfit: "French maid",
    prop: "Teddy bear",
}, {
    id: 9,
    accessory: null,
    background: "Neonpunk",
    expression: "Gaze star",
    hairstyle: "Double ponies",
    name: "JiaYi",
    outfit: "Kimono",
    prop: "Mic",
    prop2: "Cellphone",
}, {
    id: 10,
    accessory: null,
    background: "Night & sky",
    expression: "Brown eyes",
    hairstyle: "Double ponies",
    name: "ZhiLei",
    outfit: "Hip hop",
    prop: "Skateboard",
}]
    // }, {
//     id: 11,
//     accessory: ,
//     background: ,
//     expression: ,
//     hairstyle: ,
//     name: ,
//     outfit: ,
//     prop: null,
// }]